// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: cast_channel.proto

package castpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CastMessage_ProtocolVersion int32

const (
	CastMessage_CASTV2_1_0 CastMessage_ProtocolVersion = 0
)

// Enum value maps for CastMessage_ProtocolVersion.
var (
	CastMessage_ProtocolVersion_name = map[int32]string{
		0: "CASTV2_1_0",
	}
	CastMessage_ProtocolVersion_value = map[string]int32{
		"CASTV2_1_0": 0,
	}
)

func (x CastMessage_ProtocolVersion) Enum() *CastMessage_ProtocolVersion {
	p := new(CastMessage_ProtocolVersion)
	*p = x
	return p
}

func (x CastMessage_ProtocolVersion) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CastMessage_ProtocolVersion) Descriptor() protoreflect.EnumDescriptor {
	return file_cast_channel_proto_enumTypes[0].Descriptor()
}

func (CastMessage_ProtocolVersion) Type() protoreflect.EnumType {
	return &file_cast_channel_proto_enumTypes[0]
}

func (x CastMessage_ProtocolVersion) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *CastMessage_ProtocolVersion) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = CastMessage_ProtocolVersion(num)
	return nil
}

// Deprecated: Use CastMessage_ProtocolVersion.Descriptor instead.
func (CastMessage_ProtocolVersion) EnumDescriptor() ([]byte, []int) {
	return file_cast_channel_proto_rawDescGZIP(), []int{0, 0}
}

type CastMessage_PayloadType int32

const (
	CastMessage_STRING CastMessage_PayloadType = 0
	CastMessage_BINARY CastMessage_PayloadType = 1
)

// Enum value maps for CastMessage_PayloadType.
var (
	CastMessage_PayloadType_name = map[int32]string{
		0: "STRING",
		1: "BINARY",
	}
	CastMessage_PayloadType_value = map[string]int32{
		"STRING": 0,
		"BINARY": 1,
	}
)

func (x CastMessage_PayloadType) Enum() *CastMessage_PayloadType {
	p := new(CastMessage_PayloadType)
	*p = x
	return p
}

func (x CastMessage_PayloadType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CastMessage_PayloadType) Descriptor() protoreflect.EnumDescriptor {
	return file_cast_channel_proto_enumTypes[1].Descriptor()
}

func (CastMessage_PayloadType) Type() protoreflect.EnumType {
	return &file_cast_channel_proto_enumTypes[1]
}

func (x CastMessage_PayloadType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *CastMessage_PayloadType) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = CastMessage_PayloadType(num)
	return nil
}

// Deprecated: Use CastMessage_PayloadType.Descriptor instead.
func (CastMessage_PayloadType) EnumDescriptor() ([]byte, []int) {
	return file_cast_channel_proto_rawDescGZIP(), []int{0, 1}
}

type AuthError_ErrorType int32

const (
	AuthError_INTERNAL_ERROR AuthError_ErrorType = 0
	AuthError_NO_TLS         AuthError_ErrorType = 1
)

// Enum value maps for AuthError_ErrorType.
var (
	AuthError_ErrorType_name = map[int32]string{
		0: "INTERNAL_ERROR",
		1: "NO_TLS",
	}
	AuthError_ErrorType_value = map[string]int32{
		"INTERNAL_ERROR": 0,
		"NO_TLS":         1,
	}
)

func (x AuthError_ErrorType) Enum() *AuthError_ErrorType {
	p := new(AuthError_ErrorType)
	*p = x
	return p
}

func (x AuthError_ErrorType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AuthError_ErrorType) Descriptor() protoreflect.EnumDescriptor {
	return file_cast_channel_proto_enumTypes[2].Descriptor()
}

func (AuthError_ErrorType) Type() protoreflect.EnumType {
	return &file_cast_channel_proto_enumTypes[2]
}

func (x AuthError_ErrorType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *AuthError_ErrorType) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = AuthError_ErrorType(num)
	return nil
}

// Deprecated: Use AuthError_ErrorType.Descriptor instead.
func (AuthError_ErrorType) EnumDescriptor() ([]byte, []int) {
	return file_cast_channel_proto_rawDescGZIP(), []int{3, 0}
}

type CastMessage struct {
	state           protoimpl.MessageState       `protogen:"open.v1"`
	ProtocolVersion *CastMessage_ProtocolVersion `protobuf:"varint,1,req,name=protocol_version,json=protocolVersion,enum=cast_channel.CastMessage_ProtocolVersion" json:"protocol_version,omitempty"`
	SourceId        *string                      `protobuf:"bytes,2,req,name=source_id,json=sourceId" json:"source_id,omitempty"`
	DestinationId   *string                      `protobuf:"bytes,3,req,name=destination_id,json=destinationId" json:"destination_id,omitempty"`
	Namespace       *string                      `protobuf:"bytes,4,req,name=namespace" json:"namespace,omitempty"`
	PayloadType     *CastMessage_PayloadType     `protobuf:"varint,5,req,name=payload_type,json=payloadType,enum=cast_channel.CastMessage_PayloadType" json:"payload_type,omitempty"`
	PayloadUtf8     *string                      `protobuf:"bytes,6,opt,name=payload_utf8,json=payloadUtf8" json:"payload_utf8,omitempty"`
	PayloadBinary   []byte                       `protobuf:"bytes,7,opt,name=payload_binary,json=payloadBinary" json:"payload_binary,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CastMessage) Reset() {
	*x = CastMessage{}
	mi := &file_cast_channel_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CastMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CastMessage) ProtoMessage() {}

func (x *CastMessage) ProtoReflect() protoreflect.Message {
	mi := &file_cast_channel_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CastMessage.ProtoReflect.Descriptor instead.
func (*CastMessage) Descriptor() ([]byte, []int) {
	return file_cast_channel_proto_rawDescGZIP(), []int{0}
}

func (x *CastMessage) GetProtocolVersion() CastMessage_ProtocolVersion {
	if x != nil && x.ProtocolVersion != nil {
		return *x.ProtocolVersion
	}
	return CastMessage_CASTV2_1_0
}

func (x *CastMessage) GetSourceId() string {
	if x != nil && x.SourceId != nil {
		return *x.SourceId
	}
	return ""
}

func (x *CastMessage) GetDestinationId() string {
	if x != nil && x.DestinationId != nil {
		return *x.DestinationId
	}
	return ""
}

func (x *CastMessage) GetNamespace() string {
	if x != nil && x.Namespace != nil {
		return *x.Namespace
	}
	return ""
}

func (x *CastMessage) GetPayloadType() CastMessage_PayloadType {
	if x != nil && x.PayloadType != nil {
		return *x.PayloadType
	}
	return CastMessage_STRING
}

func (x *CastMessage) GetPayloadUtf8() string {
	if x != nil && x.PayloadUtf8 != nil {
		return *x.PayloadUtf8
	}
	return ""
}

func (x *CastMessage) GetPayloadBinary() []byte {
	if x != nil {
		return x.PayloadBinary
	}
	return nil
}

type AuthChallenge struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthChallenge) Reset() {
	*x = AuthChallenge{}
	mi := &file_cast_channel_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthChallenge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthChallenge) ProtoMessage() {}

func (x *AuthChallenge) ProtoReflect() protoreflect.Message {
	mi := &file_cast_channel_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthChallenge.ProtoReflect.Descriptor instead.
func (*AuthChallenge) Descriptor() ([]byte, []int) {
	return file_cast_channel_proto_rawDescGZIP(), []int{1}
}

type AuthResponse struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Signature             []byte                 `protobuf:"bytes,1,req,name=signature" json:"signature,omitempty"`
	ClientAuthCertificate []byte                 `protobuf:"bytes,2,req,name=client_auth_certificate,json=clientAuthCertificate" json:"client_auth_certificate,omitempty"`
	ClientCa              [][]byte               `protobuf:"bytes,3,rep,name=client_ca,json=clientCa" json:"client_ca,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *AuthResponse) Reset() {
	*x = AuthResponse{}
	mi := &file_cast_channel_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthResponse) ProtoMessage() {}

func (x *AuthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cast_channel_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthResponse.ProtoReflect.Descriptor instead.
func (*AuthResponse) Descriptor() ([]byte, []int) {
	return file_cast_channel_proto_rawDescGZIP(), []int{2}
}

func (x *AuthResponse) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *AuthResponse) GetClientAuthCertificate() []byte {
	if x != nil {
		return x.ClientAuthCertificate
	}
	return nil
}

func (x *AuthResponse) GetClientCa() [][]byte {
	if x != nil {
		return x.ClientCa
	}
	return nil
}

type AuthError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ErrorType     *AuthError_ErrorType   `protobuf:"varint,1,req,name=error_type,json=errorType,enum=cast_channel.AuthError_ErrorType" json:"error_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthError) Reset() {
	*x = AuthError{}
	mi := &file_cast_channel_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthError) ProtoMessage() {}

func (x *AuthError) ProtoReflect() protoreflect.Message {
	mi := &file_cast_channel_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthError.ProtoReflect.Descriptor instead.
func (*AuthError) Descriptor() ([]byte, []int) {
	return file_cast_channel_proto_rawDescGZIP(), []int{3}
}

func (x *AuthError) GetErrorType() AuthError_ErrorType {
	if x != nil && x.ErrorType != nil {
		return *x.ErrorType
	}
	return AuthError_INTERNAL_ERROR
}

type DeviceAuthMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Challenge     *AuthChallenge         `protobuf:"bytes,1,opt,name=challenge" json:"challenge,omitempty"`
	Response      *AuthResponse          `protobuf:"bytes,2,opt,name=response" json:"response,omitempty"`
	Error         *AuthError             `protobuf:"bytes,3,opt,name=error" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceAuthMessage) Reset() {
	*x = DeviceAuthMessage{}
	mi := &file_cast_channel_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceAuthMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceAuthMessage) ProtoMessage() {}

func (x *DeviceAuthMessage) ProtoReflect() protoreflect.Message {
	mi := &file_cast_channel_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceAuthMessage.ProtoReflect.Descriptor instead.
func (*DeviceAuthMessage) Descriptor() ([]byte, []int) {
	return file_cast_channel_proto_rawDescGZIP(), []int{4}
}

func (x *DeviceAuthMessage) GetChallenge() *AuthChallenge {
	if x != nil {
		return x.Challenge
	}
	return nil
}

func (x *DeviceAuthMessage) GetResponse() *AuthResponse {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *DeviceAuthMessage) GetError() *AuthError {
	if x != nil {
		return x.Error
	}
	return nil
}

var File_cast_channel_proto protoreflect.FileDescriptor

const file_cast_channel_proto_rawDesc = "" +
	"\n" +
	"\x12cast_channel.proto\x12\fcast_channel\"\xa3\x03\n" +
	"\vCastMessage\x12T\n" +
	"\x10protocol_version\x18\x01 \x02(\x0e2).cast_channel.CastMessage.ProtocolVersionR\x0fprotocolVersion\x12\x1b\n" +
	"\tsource_id\x18\x02 \x02(\tR\bsourceId\x12%\n" +
	"\x0edestination_id\x18\x03 \x02(\tR\rdestinationId\x12\x1c\n" +
	"\tnamespace\x18\x04 \x02(\tR\tnamespace\x12H\n" +
	"\fpayload_type\x18\x05 \x02(\x0e2%.cast_channel.CastMessage.PayloadTypeR\vpayloadType\x12!\n" +
	"\fpayload_utf8\x18\x06 \x01(\tR\vpayloadUtf8\x12%\n" +
	"\x0epayload_binary\x18\a \x01(\fR\rpayloadBinary\"!\n" +
	"\x0fProtocolVersion\x12\x0e\n" +
	"\n" +
	"CASTV2_1_0\x10\x00\"%\n" +
	"\vPayloadType\x12\n" +
	"\n" +
	"\x06STRING\x10\x00\x12\n" +
	"\n" +
	"\x06BINARY\x10\x01\"\x0f\n" +
	"\rAuthChallenge\"\x81\x01\n" +
	"\fAuthResponse\x12\x1c\n" +
	"\tsignature\x18\x01 \x02(\fR\tsignature\x126\n" +
	"\x17client_auth_certificate\x18\x02 \x02(\fR\x15clientAuthCertificate\x12\x1b\n" +
	"\tclient_ca\x18\x03 \x03(\fR\bclientCa\"z\n" +
	"\tAuthError\x12@\n" +
	"\n" +
	"error_type\x18\x01 \x02(\x0e2!.cast_channel.AuthError.ErrorTypeR\terrorType\"+\n" +
	"\tErrorType\x12\x12\n" +
	"\x0eINTERNAL_ERROR\x10\x00\x12\n" +
	"\n" +
	"\x06NO_TLS\x10\x01\"\xb5\x01\n" +
	"\x11DeviceAuthMessage\x129\n" +
	"\tchallenge\x18\x01 \x01(\v2\x1b.cast_channel.AuthChallengeR\tchallenge\x126\n" +
	"\bresponse\x18\x02 \x01(\v2\x1a.cast_channel.AuthResponseR\bresponse\x12-\n" +
	"\x05error\x18\x03 \x01(\v2\x17.cast_channel.AuthErrorR\x05errorB\x16Z\x14cast-receiver/castpb"

var (
	file_cast_channel_proto_rawDescOnce sync.Once
	file_cast_channel_proto_rawDescData []byte
)

func file_cast_channel_proto_rawDescGZIP() []byte {
	file_cast_channel_proto_rawDescOnce.Do(func() {
		file_cast_channel_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cast_channel_proto_rawDesc), len(file_cast_channel_proto_rawDesc)))
	})
	return file_cast_channel_proto_rawDescData
}

var file_cast_channel_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_cast_channel_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_cast_channel_proto_goTypes = []any{
	(CastMessage_ProtocolVersion)(0), // 0: cast_channel.CastMessage.ProtocolVersion
	(CastMessage_PayloadType)(0),     // 1: cast_channel.CastMessage.PayloadType
	(AuthError_ErrorType)(0),         // 2: cast_channel.AuthError.ErrorType
	(*CastMessage)(nil),              // 3: cast_channel.CastMessage
	(*AuthChallenge)(nil),            // 4: cast_channel.AuthChallenge
	(*AuthResponse)(nil),             // 5: cast_channel.AuthResponse
	(*AuthError)(nil),                // 6: cast_channel.AuthError
	(*DeviceAuthMessage)(nil),        // 7: cast_channel.DeviceAuthMessage
}
var file_cast_channel_proto_depIdxs = []int32{
	0, // 0: cast_channel.CastMessage.protocol_version:type_name -> cast_channel.CastMessage.ProtocolVersion
	1, // 1: cast_channel.CastMessage.payload_type:type_name -> cast_channel.CastMessage.PayloadType
	2, // 2: cast_channel.AuthError.error_type:type_name -> cast_channel.AuthError.ErrorType
	4, // 3: cast_channel.DeviceAuthMessage.challenge:type_name -> cast_channel.AuthChallenge
	5, // 4: cast_channel.DeviceAuthMessage.response:type_name -> cast_channel.AuthResponse
	6, // 5: cast_channel.DeviceAuthMessage.error:type_name -> cast_channel.AuthError
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_cast_channel_proto_init() }
func file_cast_channel_proto_init() {
	if File_cast_channel_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cast_channel_proto_rawDesc), len(file_cast_channel_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cast_channel_proto_goTypes,
		DependencyIndexes: file_cast_channel_proto_depIdxs,
		EnumInfos:         file_cast_channel_proto_enumTypes,
		MessageInfos:      file_cast_channel_proto_msgTypes,
	}.Build()
	File_cast_channel_proto = out.File
	file_cast_channel_proto_goTypes = nil
	file_cast_channel_proto_depIdxs = nil
}
